name: Alerta a ntfy - Push a Main

on:
  push:
    branches:
      - main

jobs:
  enviar-a-ntfy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Enviar notificación a ntfy
        run: |
          curl -H "Title: Push exitoso en main" \
               -H "Priority: high" \
               -H "Tags: github,alert" \
               -H "Click: ${{ github.event.head_commit.url }}" \
               -d "Repositorio: ${{ github.repository }} Autor: ${{ github.actor }} Commit: ${{ github.event.head_commit.message }} Ver cambios: ${{ github.event.head_commit.url }}" \ https://ntfy.sh/devops-itla
