name: Alerta a ntfy - Push a Main

on:
  push:
    branches:
      - main

jobs:
  enviar-a-ntfy:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar notificación a ntfy
        run: curl -H "Title:Push exitoso en main" -d "Daniel Augusto" https://ntfy.sh/devops-itla
